version: "3.3"
services:
  db:
    image: "postgres"
    container_name: "client2sources"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "54320:5432"
  redis-master:
    image: 'bitnami/redis:latest'
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    ports:
      - '6379'
    environment:
      - REDIS_HOST=redis
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=master
    volumes:
      - '../redis-data/redis:/bitnami/redis'
  redis-replica:
    image: 'bitnami/redis:latest'
    ports:
      - '6379:6379'
    depends_on:
      - redis-master
    environment:
      - REDIS_HOST=redis
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=master
      - REDIS_PASSWORD=replica