version: "3.6"

services:
  postgresdb:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "54320:5432"  

  redis-master:
    image: 'bitnami/redis:latest'
    ports:
      - '6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=redis
    volumes:
      - '../redis-data/redis-master:/bitnami/redis'
    networks:
      - redis-network

  redis-replica:
    image: 'bitnami/redis:latest'
    ports:
      - '6379'
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=redis
      - REDIS_PASSWORD=redis
    volumes:
        - '../redis-data/redis-slave:/bitnami/redis'
    networks:
      - redis-network

  redis-sentinel:
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=redis
      - REDIS_SENTINEL_PASSWORD=sentinel
    ports:
      - '26379:26379'
    depends_on:
      - redis-master
      - redis-replica
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge